### ISSUE TITLE
Edge block breaking crash.

### ISSUE THREAD

**Issue by klos71** [idrol/ogp#12]
When breaking the last block in the current world the game crashes

**Comment by idrol** [comment]
Causes by neighbor blocks being not being generated this shouldnt hapen because there should always be 1 neighbor chunk loaded to a visible chunk.

**Comment by idrol** [comment]
Changing to major as this shouldnt actualy be a problem once the infinite world is implemented

**Comment by idrol** [comment]
Fixed with infinite world as you cant reach the edge
