### ISSUE TITLE
Basic survival

### ISSUE THREAD

**Issue by idrol** [idrol/ogp#18]
TODO LIST:
- [x] Woriking inventory system
 - [x] Working ui that you can click
 - [x] Fix issue with rendering blocks attached to mouse.
 - [x] Fix issue with being able to pick up items inside the inventory
- [x] Block have a hardnes which determines how long they take to break.
- [x] Blocks drop items when broken.
- [x] Crafting system
- [x] Tool rendering
- [x] Finnish issues #16 and #17 
- [x] Textures @klos71

**Comment by klos71** [comment]
Also to add is an "ingame" GUI to display: health, armor, invetory, and more to add

**Comment by idrol** [comment]
The basic code is now implemented to support survival.
