### ISSUE TITLE
Colision

### ISSUE THREAD

**Issue by klos71** [idrol/ogp#3]
when trying to go up with a block above you, you will go thru the first block and the collisoon will react on the second block

**Comment by idrol** [comment]
After some more testing this seems to lead to the conlusion that the collision meshes are 1 block higher that the rendering of the world. Wich would mean that the rendering is incorrect or the collision is incorrect but close investigation of the rendering doesn't show anything that could be related to the collision detection. Now moving this to critical as it could afect other parts of the game.
