### ISSUE TITLE
Java port bug list

### ISSUE THREAD

**Issue by idrol** [idrol/ogp#65]
- [x] ConcurrentModificationExceptions when picking up items
- [x] Block break timer doesnt stop
- [x] Pressing back or quit i game menu crashes the game.
- [x] World doesnt render
- [x] Text renders incorectly
- [x] World handler crash
- [x] Collision doesnt fully work seems to affect meshing to some extent only in certain directions
- [x] Chunks are not meshed when moving in a negative direction not port issue existed before port
- [x] Complete multiplayer code
- [x] Ui rendering in wrong locations
- [x] Cannot open crafting table with right click
- [x] Crafting output slot is eating items/blocks
- [x] Crafting output slot doesnt render text/not creating text model.

**Comment by klos71** [comment]
Updated with multiplayer code
